include:
  remote: https://raw.githubusercontent.com/thegangtechnology/devop-templates/main/gitlab/common/v1/common.yml

image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:stable

stages:
  - Lint
  - Tests
  - Static Test

variables:
  NODE_VERSION: "14.15"
  PROJECT_NAME: ""
  SONAR_TOKEN: "$SONAR_TOKEN"
  SONAR_HOST_URL: "https://sonarqube.dev.thegang.tech"

workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'
    - if: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "develop"'

lint:
  stage: Lint
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:${NODE_VERSION}
  extends:
    - .npm-caching
  before_script:
    - npm install -g eslint
    - npm install
    - eslint --version || exit 1
  script:
    - npm run lint
    - npm run build # ensure it builds

test-and-coverage:
  stage: Tests
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:${NODE_VERSION}
  extends:
    - .npm-caching
  before_script:
    - npm install -g eslint
    - npm install
    - eslint --version || exit 1
  script:
    - npm run test -- --collectCoverage true
    - npm run build
  artifacts:
    paths:
      - coverage/lcov.info
    expire_in: 1 week

sonarqube:
  stage: Static Test
  dependencies:
    - test-and-coverage
  extends:
    - .run-sonarqube-javascript
